import { Highlight } from './highlight.tsx';

const Text = () => {
    const wordList = [
        'apple',
        'banana',
        'cherry',
        'date',
        'elderberry',
        'fig',
        'grape',
        'honeydew',
        'kiwi',
        'lemon',
        'mango',
        'orange',
        'papaya',
        'quince',
        'raspberry',
        'strawberry',
        'blueberry',
        'blackberry',
        'watermelon',
        'pineapple',
        'pear',
        'peach',
        'plum',
        'apricot',
        'cranberry',
        'grapefruit',
        'lime',
        'coconut',
        'pomegranate',
        'dragonfruit',
        'guava',
        'lychee',
        'passionfruit',
        'mulberry',
        'boysenberry',
        'kiwifruit',
        'cantaloupe',
        'tangerine',
        'apricot',
        'nectarine',
        'persimmon',
        'starfruit',
        'cucumber',
        'tomato',
        'bell pepper',
        'carrot',
        'lettuce',
        'broccoli',
        'cauliflower',
        'zucchini',
        'spinach',
        'kale',
        'potato',
        'sweet potato',
        'onion',
        'garlic',
        'ginger',
        'pumpkin',
        'butternut squash',
        'acorn squash',
        'avocado',
        'eggplant',
        'asparagus',
        'peas',
        'corn',
        'green beans',
        'cabbage',
        'celery',
        'radish',
        'turnip',
        'beet',
        'mushroom',
        'parsley',
        'cilantro',
        'thyme',
        'rosemary',
        'basil',
        'oregano',
        'mint',
        'sage',
        'dill',
        'cinnamon',
        'nutmeg',
        'paprika',
        'cumin',
        'coriander',
        'cardamom',
        'turmeric',
        'cayenne pepper',
        'mustard',
        'vanilla',
        'chocolate',
        'caramel',
        'honey',
        'maple syrup',
        'jam',
        'jelly',
        'marmalade',
        'peanut butter',
        'almond butter',
        'cashew butter',
        'hazelnut spread',
        'hummus',
        'salsa',
        'guacamole',
        'ketchup',
        'mayonnaise',
        'mustard',
        'ranch dressing',
    ];

    return (
        <div>
            <Highlight searchText={wordList} />
        </div>
    );
};

export default Text;
